language: php

php:
  - 7.3
  - 8.0
jobs:
  fast_finish: true
  include:
    - php: 8.0
      env: DB=mysql:5.7
    - php: 8.0
      env: DB=mysql:8.0
    - php: 7.3
      env: DB=mysql:5.7
    - php: 7.3
      env: DB=mysql:8.0

services:
  - mysql

dist: xenial
sudo: required

before_script:
  - mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -u root -e "GRANT ALL ON *.* TO 'homestead'@'localhost';"
  - cp .env.travis .env
  - composer install

script:
  - ./test
