language: php

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

dist: xenial
sudo: required

before_script:
  - mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -u root -e "GRANT ALL ON *.* TO 'homestead'@'localhost';"
  - cp .env.travis .env
  - composer install

script:
  - ./test
