#!/bin/bash

DB_HOST="192.168.10.10"
DB_USERNAME="homestead"
DB_PASSWORD="secret"

mysql --host=$DB_HOST --user=$DB_USERNAME --password=$DB_PASSWORD -e "DROP DATABASE IF EXISTS settings_test;"
mysql --host=$DB_HOST --user=$DB_USERNAME --password=$DB_PASSWORD -e "CREATE DATABASE settings_test;"
