#!/bin/bash

set -e

./vendor/bin/phpcs \
  --standard=PSR2 \
  --extensions=php \
  src

./vendor/bin/phpcs \
  --standard=PSR2 \
  --extensions=php \
  tests

./rebuild_database

./vendor/bin/phpunit
